- id: 'lights_all_off'
  name: 'Lights All Off'
  icon: mdi:lightbulb-off
  entities:
    # Dimmable LED strips (6 total - light.*)
    light.led_strip_window:
      state: off
    light.led_strip_window_2:
      state: off
    light.led_strip_window_3:
      state: off
    light.led_strip_window_4:
      state: off
    light.led_strip:
      state: off
    light.led_strip_bed:
      state: off
    # All light switches (switch.*)
    switch.dining_light:
      state: off
    switch.rail_spots:
      state: off
    switch.ceiling_spots:
      state: off
    switch.rail_spots_2:
      state: off
    switch.rail_spots_3:
      state: off
    switch.ceiling_light:
      state: off
    switch.ceiling_light_2:
      state: off
    switch.ceiling_light_3:
      state: off
    switch.ceiling_light_4:
      state: off
    switch.light_2:
      state: off
    switch.terrace_lights:
      state: off
    switch.staircase_lights:
      state: off
    switch.ceiling_spots_2:
      state: off
    switch.ceiling_spots_3:
      state: off
    switch.ceiling_spots_4:
      state: off
    # LED strip switches
    switch.led_strip_countertop:
      state: off
    switch.led_strip:
      state: off
    switch.led_strip_2:
      state: off
    # Ventilators
    switch.ventilator:
      state: off
    switch.ventilator_2:
      state: off
    # Living Room ceiling spots (light.* entity)
    light.ceiling_spots:
      state: off
- id: 'ambient_10'
  name: 'Ambient 10'
  icon: mdi:movie-open
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 25
    light.led_strip_window_3:
      state: on
      brightness: 25

- id: 'ambient_70'
  name: 'Ambient 70'
  icon: mdi:brightness-6
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 178
    light.led_strip_window_3:
      state: on
      brightness: 178

- id: 'ambient_100'
  name: 'Ambient 100'
  icon: mdi:lightbulb-on
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 255
    light.led_strip_window_3:
      state: on
      brightness: 255
- id: 'ac_living_office'
  name: 'AC Living Office'
  icon: mdi:air-conditioner
  entities:
    climate.ac_living:
      state: cool
      temperature: 24
    climate.ac_office:
      state: cool
      temperature: 24

- id: 'ac_all_on'
  name: 'AC All On'
  icon: mdi:air-conditioner
  entities:
    climate.ac_living:
      state: cool
      temperature: 24
    climate.ac_bedroom:
      state: cool
      temperature: 24
    climate.ac_office:
      state: cool
      temperature: 24
    climate.ac_iacopewee:
      state: cool
      temperature: 24

- id: 'ac_all_off'
  name: 'AC All Off'
  icon: mdi:snowflake-off
  entities:
    climate.ac_living:
      state: off
    climate.ac_bedroom:
      state: off
    climate.ac_office:
      state: off
    climate.ac_iacopewee:
      state: off
- id: 'everything_off'
  name: 'Everything Off'
  icon: mdi:home-export-outline
  entities:
    # All ACs (4 total)
    climate.ac_living:
      state: off
    climate.ac_bedroom:
      state: off
    climate.ac_office:
      state: off
    climate.ac_iacopewee:
      state: off
    # All dimmable LED strips (6 total)
    light.led_strip_window:
      state: off
    light.led_strip_window_2:
      state: off
    light.led_strip_window_3:
      state: off
    light.led_strip_window_4:
      state: off
    light.led_strip:
      state: off
    light.led_strip_bed:
      state: off
    # All light switches
    switch.dining_light:
      state: off
    switch.rail_spots:
      state: off
    switch.ceiling_spots:
      state: off
    switch.rail_spots_2:
      state: off
    switch.rail_spots_3:
      state: off
    switch.ceiling_light:
      state: off
    switch.ceiling_light_2:
      state: off
    switch.ceiling_light_3:
      state: off
    switch.ceiling_light_4:
      state: off
    switch.light_2:
      state: off
    switch.terrace_lights:
      state: off
    switch.staircase_lights:
      state: off
    switch.ceiling_spots_2:
      state: off
    switch.ceiling_spots_3:
      state: off
    switch.ceiling_spots_4:
      state: off
    switch.led_strip_countertop:
      state: off
    switch.led_strip:
      state: off
    switch.led_strip_2:
      state: off
    switch.ventilator:
      state: off
    switch.ventilator_2:
      state: off
    light.ceiling_spots:
      state: off
    # TVs (2 total)
    media_player.77_oled:
      state: off
    media_player.lg_webos_tv_oled48c22lb:
      state: off
    # Kitchen appliances (cooktop & oven power)
    switch.cooktop_power:
      state: off
    switch.oven_power:
      state: off

