- id: 'ambient_10'
  name: 'Ambient 10'
  icon: mdi:movie-open
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 25
    light.led_strip_window_3:
      state: on
      brightness: 25

- id: 'ambient_70'
  name: 'Ambient 70'
  icon: mdi:brightness-6
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 177
    light.led_strip_window_3:
      state: on
      brightness: 177

- id: 'ambient_100'
  name: 'Ambient 100'
  icon: mdi:lightbulb-on
  entities:
    light.led_strip_window_2:
      state: on
      brightness: 254
    light.led_strip_window_3:
      state: on
      brightness: 254

- id: 'ac_living_office'
  name: 'AC Living Office'
  icon: mdi:air-conditioner
  entities:
    climate.ac_living:
      state: cool
      temperature: 24
    climate.ac_office:
      state: cool
      temperature: 24

- id: 'ac_all_on'
  name: 'AC All On'
  icon: mdi:air-conditioner
  entities:
    climate.ac_living:
      state: cool
      temperature: 24
    climate.ac_bedroom:
      state: cool
      temperature: 24
    climate.ac_office:
      state: cool
      temperature: 24
    climate.ac_iacopewee:
      state: cool
      temperature: 24

- id: 'ac_living_office_warm'
  name: 'AC Living Office Warm'
  icon: mdi:fire
  entities:
    climate.ac_living:
      state: heat
      temperature: 25
    climate.ac_office:
      state: heat
      temperature: 25

- id: 'ac_all_warm'
  name: 'AC All Warm'
  icon: mdi:fire
  entities:
    climate.ac_living:
      state: heat
      temperature: 25
    climate.ac_bedroom:
      state: heat
      temperature: 25
    climate.ac_office:
      state: heat
      temperature: 25
    climate.ac_iacopewee:
      state: heat
      temperature: 25

- id: 'ac_all_off'
  name: 'AC All Off'
  icon: mdi:snowflake-off
  entities:
    climate.ac_living:
      state: off
    climate.ac_bedroom:
      state: off
    climate.ac_office:
      state: off
    climate.ac_iacopewee:
      state: off
