lights_all_off:
  alias: "Lights All Off"
  icon: mdi:lightbulb-off
  sequence:
    - service: light.turn_off
      target:
        entity_id: "{{ states.light | map(attribute='entity_id') | list }}"
    - service: switch.turn_off
      target:
        entity_id:
          - switch.ceiling_light
          - switch.ceiling_light_2
          - switch.ceiling_light_3
          - switch.ceiling_light_4
          - switch.ceiling_spots
          - switch.ceiling_spots_2
          - switch.ceiling_spots_3
          - switch.ceiling_spots_4
          - switch.dining_light
          - switch.led_strip
          - switch.led_strip_2
          - switch.led_strip_countertop
          - switch.light_2
          - switch.rail_spots
          - switch.rail_spots_2
          - switch.rail_spots_3
          - switch.staircase_lights
          - switch.terrace_lights

everything_off:
  alias: "Everything Off"
  icon: mdi:home-export-outline
  sequence:
    - service: script.lights_all_off
    - service: climate.turn_off
      target:
        entity_id: "{{ states.climate | map(attribute='entity_id') | list }}"
    - service: media_player.turn_off
      target:
        entity_id: "{{ states.media_player | map(attribute='entity_id') | list }}"

ambient_100:
  alias: "Ambient 100"
  icon: mdi:brightness-7
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.led_strip_window_2
          - light.led_strip_window_3
      data:
        brightness: 254
